# Generated by Django 5.2 on 2025-05-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
