# Generated by Django 5.2 on 2025-05-05 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmodel_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='createdat',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='createdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
