# Generated by Django 5.2 on 2025-05-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contactmodel_createdat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='createdate',
            new_name='created_at',
        ),
    ]
