# Generated by Django 5.2 on 2025-05-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='displayas',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
