# Generated by Django 5.2 on 2025-05-05 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customusermodel_cartcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='phonenumber',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Nepali phone number starting with 97 or 98.', regex='^(97|98)\\d{8}$')]),
        ),
    ]
