# Generated by Django 5.2 on 2025-05-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customusermodel_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='phonenumber',
        ),
    ]
