# Generated by Django 5.2 on 2025-05-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_ordermodel_cartmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='cart_id',
            new_name='cartid',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='product_id',
            new_name='productid',
        ),
        migrations.RenameField(
            model_name='cartmodel',
            old_name='user_id',
            new_name='userid',
        ),
    ]
